language: python
sudo: required
dist: focal
virtualenv:
  system_site_packages: true
python:
  - "2.7"
before_install:
  - "sudo apt-add-repository -y ppa:reddit/ppa"
  - "sudo apt-get update -q"
  - "sudo apt-get install python-tinycss2-common -y"
install: 
  - "pip install http://github.com/praw-dev/praw/tarball/d0f69dc84f70fc482ac5d6e707554853fd767e29#egg=praw"
  - "wget https://raw.githubusercontent.com/reddit/reddit/master/r2/r2/lib/cssfilter.py"
  - "wget https://raw.githubusercontent.com/empyrical/reddit/a2e7ee5e5694d4b292c0f50c1d1f5afaedb6e673/r2/r2/lib/contrib/rcssmin.py"
script: "python ./validatecss.py"
deploy:
  provider: script
  script: "python ./deploy.py && git stash --all"
  skip_cleanup: true
  on:
    branch: main